version: '3'

volumes:
  database:
  static_value:
  media_value:

services:

  db:
    image: postgres:13
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    image: freelancerroma/foodgram_backend
    env_file: .env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db

  frontend:
    image: freelancerroma/foodgram_frontend
    env_file: .env
    volumes:
      - ./frontend/:/app/result_build/

  gateway:
    image: freelancerroma/foodgram_gateway
    env_file: .env
    ports:
      - 9090:80
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - backend
    restart: always