version: '3'

volumes:
  database:
  static:
  media:

services:

  db:
    image: postgres:13
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    image: freelancerroma/foodgram_backend
    env_file: .env
    volumes:
      - static:/static/
      - media:/media/ 
    depends_on:
      - db

  frontend:
    image: freelancerroma/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/

  gateway:
    image: freelancerroma/foodgram_gateway
    env_file: .env
    ports:
      - "9090:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static/ 
      - media:/media/
    depends_on:
      - frontend
      - backend
    restart: always