version: '3'

volumes:
  database:
  static_value:
  media_value:

services:

  db:
    image: postgres:13
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    image: freelancerroma/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/media/ 
    depends_on:
      - db

  frontend:
    image: freelancerroma/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/

  gateway:
    image: freelancerroma/foodgram_gateway
    ports:
      - "9090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/ 
      - media:/media/
    depends_on:
      - backend
      - frontend
    restart: always