version: '3'

volumes:
  database:
  static_value:
  media_value:

services:

  db:
    image: postgres:13
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_value:/backend_static
      - media_value:/media
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/result_build

  gateway:
    build: ./nginx/
    ports:
      - "9090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/static
      - media_value:/media
    depends_on:
      - backend
    restart: always