version: '3.3'

volumes:
  foodgram_data:
  foodgram_static:
  foodgram_media:

services:

  foodgram_db:
    image: postgres:13
    env_file: .env
    volumes:
      - foodgram_data:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    env_file: .env
    volumes:
      - foodgram_static:/app/static
      - foodgram_media:/app/media
    depends_on:
      - foodgram_db

  frontend:
    build: ./frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - foodgram_static:/frontend_static/
    depends_on:
      - foodgram_db
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "9090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - foodgram_static:/var/html/static/
      - foodgram_media:/var/html/media/
    depends_on:
      - backend
      - frontend
      - foodgram_db